services:
  tagger-postgres:
    image: postgres:14
    volumes:
      - ./tagger-postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRESQL_TAGGER_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_TAGGER_PASS}
      POSTGRES_DB: ${POSTGRESQL_TAGGER_DB}
    ports:
      - ${POSTGRESQL_TAGGER_PORT}:5432
