tagger:
  access_token: ${TAGGER_TOKEN}
  is_test: 'false'
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Europe/Moscow
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_TAGGER_CONTAINER_NAME}/${POSTGRESQL_TAGGER_DB}
    username: ${POSTGRESQL_TAGGER_USER}
    password: ${POSTGRESQL_TAGGER_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  web:
    locale: ru_RU