---

- name: Update Docker Compose containers
  hosts: tagger
  gather_facts: no
  become: yes

  tasks:
    - name: Pull image
      community.docker.docker_compose_v2_pull:
        project_src: "{{ project_src }}"
      register: output

    - name: Recreate services
      community.docker.docker_compose_v2:
        project_src: "{{ project_src }}"
      register: output
